# Generated by Django 5.0.1 on 2024-02-13 11:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_remove_serviceprovider_place_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='serviceprovider',
            name='Location',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='app.locations'),
        ),
    ]
