# Generated by Django 5.0.1 on 2024-02-14 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_requests_accept_requests_decline_requests_pending'),
    ]

    operations = [
        migrations.AddField(
            model_name='requests',
            name='description',
            field=models.TextField(blank=True),
        ),
    ]
