# Generated by Django 5.0.1 on 2024-02-14 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_requests_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='serviceprovider',
            name='approve',
            field=models.BooleanField(default=False),
        ),
    ]
